name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Correct the version to 17 since you mentioned 22 which might not be available
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker docker-compose

      - name: Run Docker Compose
        run: docker-compose up -d
